Authentication done
iBoss-Africa/clrd_auth_api pull request #1
Opened 2024-02-16 13:28 UTC by WiseoneO

2024-02-16 14:25 UTC, Chibuzo requested changes
1. You remove .env,sample file again. We need ot.
2. Let's have validation in one place. I'll suggest DTO rather than schema validation. We shouldn't use the two anyway.

2024-02-16 14:25 UTC, Chibuzo commented on src/auth/auth.service.ts
> +        const hashPassword = await bcrypt.hash(password, 10);
Let's create a config file and make SALT a constant, then import it from there and use here.
 
**General note**, having a number like this doesn't say anything about the value. Putting it in a variable gives it more context/meaning.

2024-02-16 14:25 UTC, Chibuzo commented on src/auth/auth.service.ts
> +        return {token};
```suggestion
        return {token, user: newUser };
```

2024-02-16 14:25 UTC, Chibuzo commented on src/auth/auth.service.ts
> +            throw new NotFoundException('Invali email or password')
```suggestion
            throw new NotFoundException('Invalid email or password')
```

2024-02-16 14:25 UTC, Chibuzo commented on src/auth/auth.service.ts
> +            throw new UnauthorizedException('Invali email or password');
```suggestion
            throw new UnauthorizedException('Invalid email or password');
```

2024-02-16 14:25 UTC, Chibuzo commented on src/users/users.service.ts
> +                email: email
`getOne` method shouldn't be tied to a named parameter/criteria. Let's pass in an object instead so that different criteria could be used to find one record

```suggestion
    async getOne(criteria: Object): Promise<User>{
        try{
                // Check for the user with the id
            const user = await this.prisma.user.findUnique({ where: 
                { ...criteria, deleted: false
```

2024-02-16 14:25 UTC, Chibuzo commented on src/utils/apiFeatures.utils.ts
> +        };
Isn't this alot? id would have been enough

2024-02-16 14:48 UTC, WiseoneO commented on src/auth/auth.service.ts
> +        return {token};
Noted

2024-02-16 14:49 UTC, WiseoneO commented on src/auth/auth.service.ts
> +            throw new NotFoundException('Invali email or password')
noted

2024-02-16 15:05 UTC, WiseoneO commented on src/utils/apiFeatures.utils.ts
> +        };
the id and the email could be just fine

2024-02-16 15:31 UTC, WiseoneO commented on src/utils/apiFeatures.utils.ts
> +        };
done

2024-02-20 12:04 UTC, Chibuzo commented on src/users/users.service.ts
> +        }
This validation should happen in a middleware

2024-02-20 12:04 UTC, Chibuzo commented on src/users/users.service.ts
> +                throw new UnauthorizedException('you can perform this operation!')
Middleware. Unauthorized operation

2024-02-21 09:36 UTC, WiseoneO commented on prisma/schema.prisma
> +  country String? @db.VarChar(7)
done

2024-02-21 09:38 UTC, WiseoneO commented on src/auth/auth.service.ts
> +        const isExist = await this.userService.getOne({email});
done

2024-02-22 13:23 UTC, merged